spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/newdb
    username: developer
    password: Kain
  jpa:
    database: mysql
    show_sql: true
    hibernate:
      ddl-auto: create-drop
mvc:
path match:
matching-strategy: ant_path_matcher
server:
port: 8080